name: psychologist

services:
  api:
    build: Psychologist.Server
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    build: Psychologist.Client
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
  
  db:
    image: postgres:16.2
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: psychologist

volumes:
  db:

# docker-compose up --build